services:
  web:
    volumes:
      - code:/code
  app:
    volumes:
      - code:/code
  js:
    volumes:
      - code:/code

x-mutagen:
  sync:
    code:
      alpha: "."
      beta: "volume://code"
      mode: "two-way-resolved"
      ignore:
        vcs: true
      permissions:
        defaultFileMode: 0666
        defaultDirectoryMode: 0777
      configurationBeta:
        permissions:
          defaultOwner: id:0
          defaultGroup: id:0
