services:
  app:
    build:
      target: base
    depends_on:
      - js
      - db
    networks:
      - default
      - docker_default
    volumes:
      - .:/code
      - ./docker/unit/zz-custom.ini:/usr/local/etc/php/zz-custom.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lily.rule=Host(`lily.localhost`)"
  js:
    image: node:22.11.0-slim
    working_dir: /code
    command: ["sh", "-c", "yarn && yarn dev"]
    volumes:
      - .:/code
    expose:
      - 80
    networks:
      - docker_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lily-hmr.rule=Host(`hmr.lily.localhost`)"
  db:
    image: mysql:9.1.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/0.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"
    networks:
      - default
      - docker_default
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  code:
  node-modules:
  db-store:

networks:
  docker_default:
    external: true
    name: docker_default
