services:
  app:
    build:
      target: base
    depends_on:
      - js
      - db
    networks:
      - default
      - docker_default
    volumes:
      - .:/code
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.new-world.rule=Host(`nw.fyui001.com`)"
      - "traefik.http.routers.new-world.tls.certresolver=myresolver"
  js:
    image: node:22.11.0-slim
    working_dir: /code
    command: ["sh", "-c", "yarn && yarn build && /bin/bash"]
    volumes:
      - .:/code
    expose:
      - 80
    networks:
      - docker_default
    labels:
      - "traefik.enable=false"
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    tty: true
    volumes:
      - .:/code
      - ./docker/php/zz-custom.ini:/usr/local/etc/php/zz-custom.ini
    labels:
      - "traefik.enable=false"

networks:
  default: {}
  docker_default:
    external: true
    name: docker_default

volumes:
  php-vendor:
  node-modules:

