version: '3.9'
services:
  web:
    image: nginx:latest
    depends_on:
      - app
    networks:
      - default
      - docker_default
    volumes:
      - ./public:/code/public
      - ./docker/nginx/conf.d/local.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.new-world-web.rule=Host(`nw.localhost`)"
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - .:/code
      - php-vendor:/code/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - js
      - db
    labels:
      - "traefik.enable=false"
  js:
    build:
      context: .
      dockerfile: ./docker/js/Dockerfile
    tty: true
    volumes:
      - .:/code:cached
      - node-modules:/code/node_modules
    labels:
      - "traefik.enable=false"
  db:
    image: mysql:5.7
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/0.sql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    volumes:
      - memcached:/var/lib/memcached:delegated
    networks:
      - default
      - docker_default
    labels:
      - "traefik.enable=false"

networks:
  docker_default:
    name: docker_default

volumes:
  php-vendor:
  node-modules:
  memcached:
  db-store:
