version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - .:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - js
  js:
    build:
      context: .
      dockerfile: ./docker/js/Dockerfile
    volumes:
      - .:/code:cached
      - node-modules:/code/node_modules
  web:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./public:/code/public
      - ./docker/nginx/conf.d/local.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/0.sql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    volumes:
      - memcached:/var/lib/memcached:delegated
    networks:
      - default
      - docker_default

volumes:
  php-vendor:
  node-modules:
  memcached:
