services:
  web:
    image: nginx:latest
    depends_on:
      - app
    networks:
      - default
      - docker_default
    volumes:
      - ./public:/code/public
      - ./docker/nginx/conf.d/local.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.new-world.rule=Host(`nw.fyui001.com`)"
      - "traefik.http.routers.new-world.tls.certresolver=myresolver"
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - .:/code
      - php-vendor:/code/vendor
      - ./docker/php/zz-custom.ini:/usr/local/etc/php/zz-custom.ini
    depends_on:
      - js
    labels:
      - "traefik.enable=false"
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    tty: true
    volumes:
      - .:/code
      - ./docker/php/zz-custom.ini:/usr/local/etc/php/zz-custom.ini
    labels:
      - "traefik.enable=false"
  js:
    build:
      context: .
      dockerfile: ./docker/js/Dockerfile
    tty: true
    volumes:
      - .:/code:cached
      - node-modules:/code/node_modules
    labels:
      - "traefik.enable=false"

networks:
  default: {}
  docker_default:
    external: true
    name: docker_default

volumes:
  php-vendor:
  node-modules:

