version: '3'

vars:
  app_container_id:
    sh: "docker compose ps -q app"

tasks:
  init_local:
    cmds:
      - cp .env.example .env
      - cp docker-compose-local.yml compose.yml

  init_prod:
    cmds:
      - cp .env.example .env
      - cp docker-compose-prod.yml compose.yml

  init_mutagen:
    cmds:
      - curl -L https://github.com/mutagen-io/mutagen/releases/download/v0.16.2/mutagen_linux_amd64_v0.16.2.tar.gz | sudo tar -zxf - -C /usr/local/bin
      - curl -L https://github.com/mutagen-io/mutagen-compose/releases/download/v0.16.2/mutagen-compose_linux_amd64_v0.16.2.tar.gz | sudo tar -zxf - -C /usr/local/bin

  docker_build:
    cmd: docker compose build --no-cache

  composer_install:
    cmd: docker compose exec app composer install --ignore-platform-reqs

  cache_clear:
    cmds:
      - docker compose exec app php artisan cache:clear
      - docker compose exec app php artisan view:clear
      - docker compose exec app php artisan route:clear
      - docker compose exec app php artisan config:clear

  permission:
    cmd: docker compose exec app chmod -R 777 /code/storage bootstrap/cache

  migrate:
    cmd: docker compose exec app php artisan migrate

  migrate_seed:
    cmd: docker compose exec app php artisan migrate:fresh --seed --drop-views

  test_seed:
    cmd: docker compose exec app php artisan migrate:fresh --seed --drop-views --env=testing

  test:
    cmd: docker compose exec app bash -c "vendor/bin/phpunit --testdox --colors=always"

  bash:
    cmd: docker compose exec app bash

  node-ssh:
    cmd: docker compose exec js bash

  ide_helper:
    cmd: docker compose exec app php artisan ide-helper:generate

  ide_helper_models:
    cmd: docker compose exec app php artisan ide-helper:models --dir="infra/EloquentModels"

  up:
    cmd: docker compose up -d

  up-mutagen:
    cmd: mutagen-compose -f compose.yml -f compose.mutagen.yml up -d

  down:
    cmd: docker compose down

  down-mutagen:
    cmd: mutagen-compose -f compose.yml -f compose.mutagen.yml down

  stop:
    cmd: docker compose stop

  setup:
    cmds:
      - task: composer_install
      - docker compose exec app php artisan key:generate
      - task: ide_helper
      - task: cache_clear
      - task: migrate_seed
      - task: test_seed
      - task: permission
      - docker compose exec app php artisan storage:link

  start_discord_bot:
    cmd: docker compose exec app php artisan discord-bot:run
