name: tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dokcer-compose build
        run: |
          cp docker-compose-local.yml docker-compose.yml
          docker-compose build
      - name: dokcer-compose up
        run: |
          cp .env.example .env
          docker-compose up -d
      - name: composer install
        run: |
          docker-compose exec -T app bash -c "composer install --no-progress --prefer-dist --optimize-autoloader"
      - name: migration
        run: |
          docker-compose exec -T app bash -c "php artisan migrate --env=testing"
      - name: phpunit
        run: |
          docker-compose exec -T app bash -c "vendor/bin/phpunit --testdox --colors=always"
