name: tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install HomeBrew
        run: |
            sudo apt-get install build-essential procps curl file git
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: instal mutagin
        run: |
          brew install mutagen-io/mutagen/mutagen-beta
          brew install mutagen-io/mutagen/mutagen-compose-beta
      - name: dokcer-compose build
        run: |
          cp docker-compose-local.yml docker-compose.yml
          docker-compose build
      - name: dokcer-compose up
        run: |
          cp .env.example .env
          mutagen-compose up -d
      - name: composer install
        run: |
           mutagen-compose exec app bash -c "composer install --no-progress --prefer-dist --optimize-autoloader"
      - name: migration
        run: |
           mutagen-compose exec app bash -c "php artisan migrate --env=testing"
      - name: phpunit
        run: |
           mutagen-compose exec app bash -c "vendor/bin/phpunit --testdox --colors=always"
