name: tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install HomeBrew
        run: |
          sudo apt-get install build-essential procps curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/runner/.bash_profile
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get install build-essential
      - name: instal mutagin
        run: |
          source ~/.bash_profile
          brew install mutagen-io/mutagen/mutagen-beta
          brew install mutagen-io/mutagen/mutagen-compose-beta
      - name: dokcer-compose build
        run: |
          cp docker-compose-local.yml docker-compose.yml
          source ~/.bash_profile
          mutagen-compose build
      - name: dokcer-compose up
        run: |
          cp .env.example .env
          source ~/.bash_profile
          mutagen-compose up -d
      - name: composer install
        run: |
          source ~/.bash_profile
          mutagen-compose exec app bash -c "composer install --no-progress --prefer-dist --optimize-autoloader"
      - name: migration
        run: |
          source ~/.bash_profile
          mutagen-compose exec app bash -c "php artisan migrate --env=testing"
      - name: phpunit
        run: |
          source ~/.bash_profile
          mutagen-compose exec app bash -c "vendor/bin/phpunit --testdox --colors=always"
