name: tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dokcer-compose up
        run: |
          # docker-compose build
          docker-compose up -d
      - name: composer install
        run: |
          docker-compose exec app composer install --no-progress --prefer-dist --optimize-autoloader
      - name: migration
        run: |
          docker-compose exec app php artisan migrate --env=testing
      - name: phpunit
        run: |
          docker-compose exec app vendor/bin/phpunit --testdox --colors=always
